run vms on el9
oVirt/ovirt-system-tests pull request #136
Opened 2022-05-01 13:53 UTC by hbraha

We need to create the VMs without QXL devices in order to run them on EL9.
The patch removes devices that use spice/qxl.

2022-05-01 13:53 UTC, hbraha commented
/ost

2022-05-01 19:07 UTC, hbraha commented
/ost

2022-05-01 19:08 UTC, hbraha commented
/ost

2022-05-02 06:59 UTC, michalskrivanek requested changes

2022-05-02 06:59 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> -            enabled=True,
this will disable smartcard and usb for all platforms, but that's ok, not so interesting

2022-05-02 06:59 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> +        pytest.skip('skip test on el9')
why? don't you want to use VNC?

2022-05-02 06:59 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> +    if console is not None:
the point here would be to test there *is* a VNC console, not a code that handles various states.

2022-05-02 06:59 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_004_basic_sanity.py
> +        pytest.skip('el9 dont use vmconsole')
it should;)

2022-05-02 06:59 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_004_basic_sanity.py
> +def add_selinux_allow_rule_for_ssh(ansible_hosts, root_dir):
why would we add anything like that? what is it trying to fix?

2022-05-17 11:49 UTC, hbraha commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> +        pytest.skip('skip test on el9')
after deleting and re-adding the VNC the video type chosen automatically is QXL which is not supported on el9. this should be resolved as part of dropping the QXL in the future.

2022-05-17 11:52 UTC, hbraha commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> +    if console is not None:
sorry, I think dont really understand what you meant here.
 the code here as the previous one, checking if vnc is there, removing it, and re-adding it. what exactly is the difference in the behviour?

2022-05-17 11:52 UTC, hbraha commented on basic-suite-master/test-scenarios/test_004_basic_sanity.py
> +        pytest.skip('el9 dont use vmconsole')
ack, fixed

2022-05-17 11:53 UTC, hbraha commented on basic-suite-master/test-scenarios/test_004_basic_sanity.py
> +def add_selinux_allow_rule_for_ssh(ansible_hosts, root_dir):
not needed anymore, the fix should be shipped with the new vmconsole package that was posted this morning.

2022-05-19 14:01 UTC, michalskrivanek approved these changes

2022-05-19 14:01 UTC, michalskrivanek commented on basic-suite-master/test-scenarios/test_002_bootstrap.py
> +    if console is not None:
hm, i don't really know what i meant, nevermind:)

2022-05-19 14:02 UTC, michalskrivanek commented
actually, please improve the commit message. It's not very...helpful

2022-05-23 08:04 UTC, hbraha commented
/ost

2022-05-25 10:31 UTC, tinez commented
/ost

2022-05-25 13:21 UTC, merged