ost_utils: vmconsole - use default byte stream
oVirt/ovirt-system-tests pull request #156
Opened 2022-05-16 20:36 UTC by erav

Align with PR#135 [1]:

By default 'Popen' processes's stdout is opened as a byte stream.
Passing the 'universal_newlines=True' argument makes the stream
automatically decoded from UTF-8.

Since we're reading the output char by char, multibyte UTF-8 characters
can break the stream with i.e.:

E UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda ...
invalid continuation byte

Let's change the output to have a form of bytes and use bytes in
comparisons too.

[1] https://github.com/oVirt/ovirt-system-tests/pull/135

Change-Id: I799faaa6617b7a1f48ce9175509eef1d7e62c4de

Signed-off-by: Eitan Raviv <eraviv@redhat.com>
Change-Id: Ic550276233f6e1908c67d4c8a3cd9d7a05a5cd4a

2022-05-17 08:29 UTC, erav commented
/ost network-suite-master

2022-05-17 17:42 UTC, erav commented
/ost network-suite-master

2022-05-18 06:19 UTC, erav commented
/ost network-suite-master

2022-05-18 13:21 UTC, erav commented
/ost network-suite-master

2022-05-19 05:02 UTC, erav commented
/ost network-suite-master

2022-05-19 09:40 UTC, tinez requested changes

2022-05-19 09:55 UTC, erav commented
/ost network-suite-master

2022-05-19 10:08 UTC, tinez commented on ost_utils/vmconsole.py
> +            while not _bytes.endswith(prompt.encode()):
We could also call `prompt = prompt.encode()` once instead of doing that with each loop iteration

2022-05-19 10:28 UTC, erav commented
/ost

2022-05-23 12:38 UTC, erav commented
/ost network-suite-master

2022-05-24 06:21 UTC, erav commented
/ost network-suite-master

2022-05-24 15:04 UTC, erav commented
/ost network-suite-master

2022-05-24 19:25 UTC, erav commented
/ost network-suite-master

2022-05-25 04:52 UTC, erav commented
/ost network-suite-master

2022-05-26 05:58 UTC, erav commented
/ost network-suite-master

2022-05-26 07:51 UTC, erav commented
/ost network-suite-master

2022-05-26 11:26 UTC, erav commented
/ost

2022-05-28 06:30 UTC, erav commented
/ost network-suite-master

2022-05-29 06:01 UTC, erav commented
/ost

2022-05-29 07:25 UTC, erav commented on ost_utils/vmconsole.py
> +            _byte = self._read()
Done

2022-05-29 07:26 UTC, erav commented on ost_utils/vmconsole.py
> +            if _byte in ('\n', '\r') or len(_byte.strip()) != 0:
Done

2022-05-29 07:26 UTC, erav commented on ost_utils/vmconsole.py
> +                _bytes = b''.join([_bytes, (self._read())])
Done

2022-05-29 07:26 UTC, erav commented on ost_utils/vmconsole.py
> +            while not _bytes.endswith(prompt.encode()):
Done

2022-05-29 11:27 UTC, merged