run el9 hosts with el8 engine
oVirt/ovirt-system-tests pull request #158
Opened 2022-05-17 14:16 UTC by hbraha

As we currently don't have an el9 engine image, this hack will provide the
option to run el9 hosts with el8 engine.

2022-05-18 08:49 UTC, tinez commented on common/helpers/ost-images.sh
> +  OST_IMAGES_ENGINE_INSTALLED=${OST_IMAGES_ENGINE_INSTALLED/el9stream/el8stream}
I think we also need to change `OST_IMAGES_NODE="${OST_IMAGES_HOST_INSTALLED}"` in this case.

2022-05-18 13:12 UTC, michalskrivanek requested changes
I don't think this file is the best place. It allows for setting the variable up front as an override. And now you'd break that and replace user-supplied variable.

I think the change should be done in the caller - ost.sh or even just the jenkins job definition.

2022-05-18 13:33 UTC, tinez commented on common/helpers/ost-images.sh
> +if [[ "$OST_IMAGES_ENGINE_INSTALLED" == *"el9stream"* ]]; then
Maybe using `OST_IMAGES_DISTRO` here would make more sense right now since we're modifying vars for more than one image.

2022-05-19 11:45 UTC, michalskrivanek commented
> > I don't think this file is the best place. It allows for setting the variable up front as an override. And now you'd break that and replace user-supplied variable.
> 
> There's no other way of testing el9stream right now than the one we enforce here - we have neither an el9stream engine image nor an el9stream-based node image available.

we do have el9stream based node, adding ost image is trivial. we just haven't done this since basic site doesn't pass yet

> This is a temporary hack for convenience. Once we have the other images available we'll get rid of that.
> 
> > I think the change should be done in the caller - ost.sh or even just the jenkins job definition.
> 
> If we put it in jenkins people will still have to modify OST code for local runs, which is annoying. If we'd like to put in `ost.sh` we'd need to replicate some logic from `ost-images.sh`. I vote for keeping it here.

it's annoying if you take my override and change it into something i do not want to run, without an option not to do that.
i.e. do OST_IMAGES_ENGINE_INSTALLED=${OST_IMAGES_ENGINE_INSTALLED:-${OST_IMAGES_DIR}/${OST_IMAGES_DISTRO/el9stream/el8stream}-engine-installed.qcow2} instead

2022-05-19 13:47 UTC, michalskrivanek commented
/ost

2022-05-19 13:51 UTC, merged