engine: Use drop-in for logging configuration
oVirt/ovirt-system-tests pull request #225
Opened 2022-07-25 15:07 UTC by tinez

Requires: https://github.com/oVirt/ovirt-engine/pull/553

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

2022-07-25 18:08 UTC, michalskrivanek requested changes
Please keep it conditional, I like to run with default logging. 

I don't think we needed multiple vars, but ok...

2022-07-26 07:12 UTC, michalskrivanek commented on ost_utils/ansible/collection.py
> +        dest='/etc/ovirt-engine/engine.conf.d/98-logging.conf',
also, let's unite the two confs. ansible is horrible, not adding a new call is a plus.

2022-07-26 09:07 UTC, tinez commented on ost_utils/ansible/collection.py
> +        dest='/etc/ovirt-engine/engine.conf.d/98-logging.conf',
Ack

2022-07-26 09:07 UTC, tinez commented
> Please keep it conditional, I like to run with default logging.

Done.

2022-07-26 09:08 UTC, tinez commented
/ost

2022-07-26 09:08 UTC, michalskrivanek approved these changes
thanks

2022-07-26 11:01 UTC, tinez commented
/ost

2022-07-26 12:51 UTC, merged