Take master SD type from env var
oVirt/ovirt-system-tests pull request #254
Opened 2022-08-31 07:50 UTC by acernek

So that we can easily switch the type.

2022-09-01 10:11 UTC, tinez requested changes
Let's also use the new constant in `test_storage_domains` from UI tests.

2022-09-01 10:11 UTC, tinez commented on ost_utils/pytest/fixtures/storage.py
> +    return os.environ.get("MASTER_SD_TYPE", "nfs")
We keep the things that come from the env in `fixtures/env.py`, so let's move this fixture there. The names for the env vars are also prefixed with `OST_`, so let's do the same here.

2022-09-13 08:10 UTC, acernek commented on ost_utils/pytest/fixtures/storage.py
> +    return os.environ.get("MASTER_SD_TYPE", "nfs")
Sorry, missed that part. Done

2022-09-13 09:54 UTC, tinez approved these changes

2022-09-13 09:54 UTC, tinez commented
/ost

2022-09-13 12:27 UTC, merged