ansible: Fix new ansible-lint warnings
oVirt/ovirt-system-tests pull request #263
Opened 2022-09-15 08:38 UTC by acernek

2022-09-15 10:26 UTC, tinez commented
/ost

2022-09-15 10:34 UTC, tinez requested changes
Didn't pass CI

2022-09-20 09:10 UTC, acernek commented
/ost

2022-09-20 10:18 UTC, acernek commented
> Didn't pass CI

Apparently we don't update the packages used for linting - doing that would however prolong the runs and there seem to be bug in the latest version of ansible-lint anyway, so I've partially reversed the change.

2022-09-26 10:06 UTC, tinez commented
/ost

2022-09-26 10:17 UTC, tinez approved these changes

2022-09-26 11:30 UTC, merged