UI tests: wait for a short time after clicking logout button
oVirt/ovirt-system-tests pull request #264
Opened 2022-09-15 12:24 UTC by ljelinkova

Logging out may take some time, especially when contacting Keycloak. Wait a bit to allow the calls to finish properly.

2022-09-15 12:24 UTC, ljelinkova commented
/ost

2022-09-15 12:42 UTC, michalskrivanek commented
ultimate solution...:-)

2022-09-15 15:44 UTC, tinez commented
/ost

2022-09-15 20:39 UTC, tinez requested changes
Unfortunately the triggered OST run failed on user portal test again. This does not seem to be sufficient.

2022-09-16 07:03 UTC, ljelinkova commented
Well, at least we know it does not work. I'll close this PR and try something else.

2022-09-16 07:03 UTC, closed without merging