README: update the custom repo URL to github
oVirt/ovirt-system-tests pull request #46
Opened 2022-03-01 11:16 UTC by avlitman

Since we moved to github we are not using jenkins.

Signed-off-by: Aviv Litman <alitman@redhat.com>

2022-03-01 11:23 UTC, tinez approved these changes

2022-03-01 11:23 UTC, tinez commented
/ost

2022-03-01 11:56 UTC, tinez requested changes
Please also mention the necessity to have the `GITHUB_TOKEN` env variable defined

2022-03-01 12:27 UTC, avlitman commented
> Please also mention the necessity to have the `GITHUB_TOKEN` env variable defined

Done.

2022-03-01 12:44 UTC, tinez requested changes

2022-03-01 12:44 UTC, tinez commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
The formatting here doesn't work as you'd expect I think - please have a look at the rich diff

2022-03-01 12:44 UTC, tinez commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
re: `appropriate permissions` personally I always forget which permissions are needed to make it work - I'd really appreciate if they were mentioned explicitly.

2022-03-01 12:46 UTC, avlitman commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
> 

I used the format from lines 72-75, I want it to be a list, I can see a preview somehow ?

2022-03-01 12:57 UTC, avlitman commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
> re: `appropriate permissions` personally I always forget which permissions are needed to make it work - I'd really appreciate if they were mentioned explicitly.

In my account under 'Select scopes' I selected the 'repo' (include all) and the 'workflow':
![Screenshot from 2022-03-01 14-55-08](https://user-images.githubusercontent.com/64130977/156172701-ee2e0fd9-deef-4c61-864c-b9ed33dc351d.png)

but really not sure if less/more is needed, can you check your permissions?

2022-03-01 13:25 UTC, avlitman commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
@tinez So it works with the 'repo'  permissions, you prefer to verify as well ? or I can add that only 'repo' are needed?

2022-03-01 15:46 UTC, tinez approved these changes

2022-03-01 15:47 UTC, tinez commented on README.md
> +*On your GitHub account go to Settings/Developer settings/Personal access tokens, and generate the token with appropriate permissions.
I did verify that too - `repo` seems to suffice

2022-03-01 15:47 UTC, tinez commented
/ost

2022-03-02 10:13 UTC, tinez approved these changes

2022-03-02 10:14 UTC, merged