coverage: Cover ost_utils and ovirtlib
oVirt/ovirt-system-tests pull request #60
Opened 2022-03-08 11:43 UTC by acernek

2022-03-09 08:18 UTC, erav commented on lagofy.sh
> +    PYTHONPATH="${PYTHONPATH}:${OST_REPO_ROOT}:${OST_REPO_ROOT}/${SUITE}" ${PYTHON} -u -B -m coverage run --source=ost_utils,network-suite-master/ovirtlib --data-file=${coverage_file} -m pytest \
there is a soft link in ost_utils to network-suite-master/ovirtlib. will specifying ost_utils be sufficient then?

2022-03-09 09:43 UTC, acernek commented on lagofy.sh
> +    PYTHONPATH="${PYTHONPATH}:${OST_REPO_ROOT}:${OST_REPO_ROOT}/${SUITE}" ${PYTHON} -u -B -m coverage run --source=ost_utils,network-suite-master/ovirtlib --data-file=${coverage_file} -m pytest \
No, It doesn't seem to suffice.

2022-03-23 11:13 UTC, tinez requested changes

2022-03-23 11:13 UTC, tinez commented on lagofy.sh
> +    PYTHONPATH="${PYTHONPATH}:${OST_REPO_ROOT}:${OST_REPO_ROOT}/${SUITE}" ${PYTHON} -u -B -m coverage html -q -d "${coverage_file}-html" --data-file=${coverage_file}
Let's have the html output in exported artifacts too

2022-03-23 11:38 UTC, acernek commented on lagofy.sh
> +    PYTHONPATH="${PYTHONPATH}:${OST_REPO_ROOT}:${OST_REPO_ROOT}/${SUITE}" ${PYTHON} -u -B -m coverage html -q -d "${coverage_file}-html" --data-file=${coverage_file}
wdym?

2022-03-23 12:34 UTC, tinez approved these changes

2022-03-29 08:26 UTC, acernek commented
/ost

2022-03-30 10:57 UTC, tinez commented
/ost

2022-04-13 08:36 UTC, tinez commented
/ost

2022-04-13 10:02 UTC, merged