add doc github workflow
oVirt/ovirt-system-tests pull request #67
Opened 2022-03-20 08:07 UTC by galitf

2022-03-21 07:12 UTC, galitf commented
/ost

2022-03-21 09:22 UTC, galitf commented
/ost

2022-03-21 09:55 UTC, galitf commented
/ost

2022-03-28 15:03 UTC, tinez requested changes

2022-03-28 15:03 UTC, tinez commented on docs/check_docs.sh
> +#!/bin/bash
Do we need this script at all? Can't we simply run `tox -e docs`?

2022-03-28 15:03 UTC, tinez commented on README.md
> +# oVirt System Tests test
Some leftover?

2022-03-29 05:56 UTC, galitf commented on .github/workflows/doc.yaml
> +name: check-docs
fixed

2022-03-29 06:19 UTC, galitf commented on .github/workflows/doc.yaml
> +  pull_request:
Changing to this, outputs: You have an error in your yaml syntax on line 2
I will check other options.

2022-03-29 07:32 UTC, galitf commented on docs/check_docs.sh
> +#!/bin/bash
done

2022-03-29 07:59 UTC, galitf commented on .github/workflows/doc.yaml
> +  pull_request:
splited to to sections

2022-03-29 08:18 UTC, galitf commented
/ost

2022-03-29 11:03 UTC, tinez approved these changes

2022-03-29 11:04 UTC, merged