add storage vm to ost runs
oVirt/ovirt-system-tests pull request #69
Opened 2022-03-21 10:15 UTC by hbraha

Currently, Except for HE, all suites use engine VM for storage,
add a separate VM for storage.

2022-03-22 14:45 UTC, tinez commented on common/deploy-scripts/setup_storage.sh
> +    if [[ $(hostname) == *"-storage"* ]] && [[ $(hostname) == *"he-"*  ]]; then
Maybe it would be better to add the management interface to storage VM in HE suite too?

2022-03-22 17:20 UTC, michalskrivanek commented on common/deploy-scripts/setup_storage.sh
> +    if [[ $(hostname) == *"-storage"* ]] && [[ $(hostname) == *"he-"*  ]]; then
it would be definitely less confusing

2022-03-22 17:22 UTC, michalskrivanek requested changes

2022-03-22 17:22 UTC, michalskrivanek commented on common/init-configs/1_engine_2_hosts.json
> +  "storage": {
you should drop these from the engine VM then

2022-03-23 11:10 UTC, tinez commented on common/init-configs/1_engine_2_hosts.json
> +  "storage": {
If we do this in this PR, we'll break OST. Only once all the suites are migrated to use the new storage VM we can do that

2022-03-29 09:46 UTC, tinez commented
/ost

2022-03-29 11:33 UTC, tinez commented on common/deploy-scripts/setup_storage.sh
> +    if [[ $(hostname) == *"-storage"* ]] && [[ $(hostname) == *"he-"*  ]]; then
Let's handle this in subsequent patches

2022-03-29 11:35 UTC, tinez approved these changes

2022-03-29 12:19 UTC, michalskrivanek approved these changes

2022-03-29 12:19 UTC, merged