Adding go-ovirt-client-tests suite
oVirt/ovirt-system-tests pull request #79
Opened 2022-03-24 08:48 UTC by emesika

This patch adds a ansible based suite named
go-ovirt-client-tests-suite-master that will test oVirt go API via the
go-ovirt.

Signed-off-by: Eli Mesika <emesika@redhat.com>

2022-03-28 12:22 UTC, michalskrivanek requested changes
I don't particularly like scripts that just runs a script. just define the env vars and run go-ovirt-client-tests-exe directly

also, IIUC it needs to be installed somehow?

also, what about the ocp installer test?

2022-03-28 12:26 UTC, janosdebugs commented
@michalskrivanek the go-ovirt-client test is a single binary that just needs to be run with the [proper environment variables set](https://github.com/oVirt/go-ovirt-client/blob/main/CONTRIBUTING.md#running-tests). We do not need the installer integration to be tested, we just need our own test suite to be run. (It is already way more extensive than the installer could ever be.)

2022-03-28 12:40 UTC, michalskrivanek commented
i think it's ok to identify which case to run based on what's available.  go-ovirt-client would be available only if you run with those artifacts - in that case it would make sense to skip the current ocp installer code and run just this one.
unless you say we should abandon the installer test altogether

2022-03-28 12:44 UTC, janosdebugs commented
The installer tests will be useful in the future, but only once we have the new version integrated. Until then, we will have breaking changes so that test will fail anyway.

2022-03-31 10:53 UTC, michalskrivanek commented
@emesika hi eli, any update?

2022-05-03 10:29 UTC, michalskrivanek requested changes
for tracking history it would be better to rename stuff from tr-suite-master and not create new copies

2022-05-03 10:29 UTC, michalskrivanek commented on .github/jenkins
> +echo "$SUITE"  | egrep '^(basic-suite-master|he-basic-suite-master|ansible-suite-master|tr-suite-master|network-suite-master|go-ovirt-client-tests-suite-master)$'
it's a terrible name. "go-suite-master" would be better.
Also if it's replacing t suite then drop it from everywhere please

2022-05-03 10:29 UTC, michalskrivanek commented on common/deploy-scripts/setup_engine.sh
> -# TODO workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2077794
don't remove this

2022-05-04 10:15 UTC, emesika commented on .github/jenkins
> +echo "$SUITE"  | egrep '^(basic-suite-master|he-basic-suite-master|ansible-suite-master|tr-suite-master|network-suite-master|go-ovirt-client-tests-suite-master)$'
Done

2022-05-04 10:15 UTC, emesika commented on common/deploy-scripts/setup_engine.sh
> -# TODO workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2077794
Done

2022-05-09 09:17 UTC, tinez commented on go-suite-master/test-scenarios/test_003_run_go_ovirt_client_tests.py
> +        for line in lines:
You don't even need to iterate here - just use `stdout` instead of `stdout_lines` and pass it directly to `o.write`

2022-05-11 07:55 UTC, emesika commented on go-suite-master/test-scenarios/test_003_run_go_ovirt_client_tests.py
> +        for line in lines:
Done

2022-05-16 09:03 UTC, tinez commented
/ost

2022-05-16 09:04 UTC, michalskrivanek commented on go-suite-master/test-scenarios/test_003_run_go_ovirt_client_tests.py
> +              OVIRT_PASSWRD={engine_password} \
OVIRT_PASSWORD

2022-05-16 09:05 UTC, michalskrivanek commented on common/deploy-scripts/setup_engine.sh
> +rpm -q rhvm || dnf downgrade -y --repo appstream postgresql-jdbc-42.2.3
please remove/rebase

2022-05-16 10:31 UTC, michalskrivanek commented on common/deploy-scripts/setup_engine.sh
> -
you don't need to touch this file at all;)

2022-05-18 08:47 UTC, tinez approved these changes

2022-05-18 09:55 UTC, tinez commented
/ost

2022-05-18 12:34 UTC, michalskrivanek approved these changes

2022-05-18 12:39 UTC, merged